document.addEventListener("DOMContentLoaded",function(){const searchInput=document.querySelector(".search-input");const copyButton=document.querySelector(".copy-button");const shareButton=document.querySelector(".share-button");const ranking=document.querySelector(".ranking");const drums=document.querySelector(".drums");const tg=window.Telegram.WebApp;const user=tg.initDataUnsafe.user;const id=user.id;let code;fetch('/api/invite/checkInviteCode',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id})}).then(response=>response.json()).then(data=>{console.log(data);if(data.success){code=data.inviteCode;const botUsername='Bones_Gamebot';searchInput.textContent=`https://t.me/${botUsername}/bones?startapp=${code}`;fetchInvitedUsers(code);updateInviteLink(code);}else{console.error('获取邀请码失败:',data.message);generateInviteCode(id);}}).catch(error=>{console.error('检查邀请码时出错:',error);});function generateInviteCode(userId){fetch("/api/invite/generateInviteCode",{method:"POST",headers:{"Content-Type":"application/json",},body:JSON.stringify({id:id})}).then(response=>response.json()).then(data=>{if(data.success){code=data.inviteCode;searchInput.textContent=`${code}`;fetchInvitedUsers(code);}else{console.error('生成邀请码失败:',data.message);}}).catch(error=>{console.error('生成邀请码时出错:',error);});}
function fetchInvitedUsers(inviteCode){fetch('/api/invite/getInvitedUsers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inviteCode:inviteCode})}).then(response=>response.json()).then(data=>{console.log("受邀：",data);if(data.success){displayInvitedUsers(data.invitedUsers);}else{console.error('获取被邀请用户失败:',data.message);}}).catch(error=>{console.error('获取被邀请用户时出错:',error);});}
function displayInvitedUsers(users){const invitedUsersList=document.querySelector('.userList');users.forEach(user=>{const userCard=document.createElement('div');userCard.className='user-list1';userCard.innerHTML=`
        <div class="user-item1">
                    <div class="user-image">
                        <img src="https://robohash.org/${user.uid}.jpg?set=set4" alt="User Image" id="avatar">
                    </div>
                    <div class="user-name">${user.uname}</div>
                    <div class="top">+ 1,161,850 <img src="../images/2.png" id="icon1"></div>
                </div>
      `;invitedUsersList.appendChild(userCard);});}
function generateShareLink(inviteCode){const botUsername='Bones_Gamebot';return`https://t.me/${botUsername}/bones?startapp=${inviteCode}`;}
function updateInviteLink(inviteCode){const shareUrl=generateShareLink(inviteCode);shareButton.onclick=function(){window.location.href=`https://t.me/share/url?url=${encodeURIComponent(shareUrl)}`;};}
if(shareButton){shareButton.addEventListener('click',()=>{if(!code){console.error('邀请码尚未可用');return;}
const botUsername='Bones_Gamebot';const shareUrl=`https://t.me/${botUsername}/bones?startapp=${code}`;const shareText=`Come take a look at this powerful application! Use my invitation code: ${code}`;const telegramShareUrl=`https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(shareText)}`;tg.openLink(telegramShareUrl);});}
copyButton.addEventListener('click',()=>{navigator.clipboard.writeText(searchInput.textContent).then(()=>{alert('Text copied to clipboard!');}).catch(err=>{console.error('Failed to copy text: ',err);});});ranking.addEventListener("click",function(){window.location.href="rankings.html";});drums.addEventListener("click",function(){window.location.href="drum.html";});});