document.addEventListener("DOMContentLoaded",function(){const drums=document.querySelector(".drums");const personal=document.querySelector(".personal");const selfname=document.querySelector("#selfname");const selflv=document.querySelector("#selfpoints");const uimg=document.querySelector("#uimg");const rankings=document.querySelector("#rankings");const ranklist=document.querySelector(".ranklist");const number=document.querySelector("#number");const tg=window.Telegram.WebApp;const user=tg.initDataUnsafe.user;const id=user.id;fetch("/api/rank/getUserCount",{method:"GET",}).then(response=>response.json()).then(data=>{console.log("用户数量:",data);number.textContent=data.userCount.toLocaleString();}).catch(error=>{console.error("Fetch error:",error);});fetch("/api/rank/ranking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id})}).then(response=>response.json()).then(data=>{console.log(data);const topPlayers=data.top20.slice(0,3);topPlayers.forEach((player,index)=>{console.log(player,index);document.getElementById(`username${index + 1}`).textContent=player.uname;pu=player.skull.toLocaleString('en-US');document.getElementById(`point${index + 1}`).textContent=`${pu}`;document.getElementById(`avatar${index + 1}`).src=`https://robohash.org/${player.uid}.jpg?set=set4`;});const rankingList=document.querySelector('.ranklist');data.top20.slice(3,20).forEach((player,index)=>{console.log(player,index);const listItem=document.createElement('div');listItem.classList.add('item');pu=player.ulevel;listItem.innerHTML=`
                    <img src="https://robohash.org/${player.uid}.jpg?set=set4" alt="" class="aimg">
                <div class="uinfo">
                    <div class="username" style="color: rgb(189,255,9); font-size: larger;"><b>${player.uname}</b></div>
                    <div class="userlv" style="color: white;">
                        <img src="../images/2.png" alt="" id="icon">
                        <div class="point"><span><b>${player.skull.toLocaleString()}</b></span></div>
                    </div>
                </div> 
                <div class="ranks" style="margin-right:7px"><b id="rankings">#${index+4}</b></div>
                `;rankingList.appendChild(listItem);});selfname.innerHTML=data.user.uname;selflv.textContent=data.user.skull.toLocaleString();rankings.textContent=`#${data.user.ranking}`;uimg.src=`https://robohash.org/${data.user.uid}.jpg?set=set4`;})
drums.addEventListener("click",function(){window.location.href="drum.html";});personal.addEventListener("click",function(){window.location.href="invitation.html";});});